angular.module('index',
    ['auth',
        'directives',
        'join',
        'main',
        'navigation',
        'ngStorage',
        'postService',
        'profile',
        'routes',
        'sign'
    ]);